*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/100pF/50V
* Murata P/N :GCH1555C1H101JE01
* Property : C = 100[pF]
* Data Generated on Jan 10, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCH1555C1H101JE01_DC0V_25degC port1 port2
C1 port1 11 1.00e-10
L2 11 12 2.65e-10
R3 12 13 7.87e-2
L4 13 14 1.32e-11
R4 13 14 6.83e-2
L5 14 15 1.76e-11
R5 14 15 2.48e-2
C6 15 16 1.08e-9
L6 15 16 6.64e-12
R6 15 16 4.45e-1
C7 16 17 1.58e-10
L7 16 17 1.89e-11
R7 16 17 1.24
C8 17 18 2.89e-11
L8 17 18 2.30e-11
R8 17 18 1.17
C9 18 port2 8.66e-12
L9 18 port2 2.98e-11
R9 18 port2 1.00e+5
R100 port1 11 1.00e+11
.ENDS GCH1555C1H101JE01_DC0V_25degC