*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/14pF/50V
* Murata P/N :GJM1555C1H140FB01
* Property : C = 14[pF]
* Data Generated on Apr 1, 2025
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-20GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GJM1555C1H140FB01_DC0V_25degC port1 port2
C1 port1 11 1.40e-11
L2 11 12 2.73e-10
R3 12 13 8.18e-2
L4 13 14 5.02e-12
R4 13 14 5.13e-2
C5 14 15 8.16e-11
L5 14 15 9.43e-12
R5 14 15 7.81
C6 15 16 2.18e-11
L6 15 16 1.39e-11
R6 15 16 21.2
C7 16 17 1.13e-10
L7 16 17 1.33e-12
R7 16 17 2.75
C8 17 18 2.75e-11
L8 17 18 3.44e-12
R8 17 18 12.3
C9 18 19 6.66e-11
L9 18 19 9.29e-13
R9 18 19 2.84
C10 19 20 1.23e-11
L10 19 20 3.83e-12
R10 19 20 23.7
C11 20 21 5.57e-12
L11 20 21 6.48e-12
R11 20 21 11.3
C12 21 port2 4.85e-12
L12 21 port2 6.31e-12
R12 21 port2 47.3
R100 port1 11 1.00e+10
.ENDS GJM1555C1H140FB01_DC0V_25degC