*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G/24pF/50V
* Murata P/N :GRM0335C1H240GA01
* Property : C = 24[pF]
* Data Generated on Jan 10, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H240GA01_DC0V_25degC port1 port2
C1 port1 11 2.40e-11
L2 11 12 9.66e-11
R3 12 13 1.49e-1
L4 13 14 1.62e-11
R4 13 14 3.11e-1
C5 14 15 3.75e-10
L5 14 15 2.55e-12
R5 14 15 3.45e-1
C6 15 16 2.54e-11
L6 15 16 1.55e-11
R6 15 16 1.77
C7 16 port2 1.67e-12
L7 16 port2 1.15e-10
R7 16 port2 1.00e+5
R100 port1 11 1.00e+10
.ENDS GRM0335C1H240GA01_DC0V_25degC