*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/10000pF/25V
* Murata P/N :GRM1555C1E103JE01
* Property : C = 10000[pF]
* Data Generated on Mar 5, 2019
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1MHz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1E103JE01_DC0V_25degC port1 port2
C1 port1 11 9.86e-9
L2 11 12 2.13e-10
R3 12 13 2.70e-3
L4 13 14 7.80e-11
R4 13 14 1.68e-1
L5 14 15 4.40e-12
R5 14 15 1.60e-1
L6 15 16 7.07e-11
R6 15 16 7.38e-3
L7 16 17 1.80e-10
R7 16 17 2.73e-3
C8 17 18 5.37e-8
L8 17 18 1.52e-11
R8 17 18 1.26e-1
C9 18 19 2.47e-8
L9 18 19 1.53e-11
R9 18 19 1.63e-1
C10 19 20 3.48e-7
L10 19 20 5.36e-13
R10 19 20 1.50e-2
C11 20 21 4.15e-8
L11 20 21 2.99e-12
R11 20 21 4.90e-2
C12 21 port2 1.84e-11
L12 21 port2 1.69e-11
R12 21 port2 12.6
R100 port1 11 1.00e+10
.ENDS GRM1555C1E103JE01_DC0V_25degC