*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G/47pF/50V
* Murata P/N :GCH0335C1H470JE01
* Property : C = 47[pF]
* Data Generated on Aug 2, 2021
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCH0335C1H470JE01_DC0V_25degC port1 port2
C1 port1 11 4.70e-11
L2 11 12 1.66e-10
R3 12 13 1.26e-1
L4 13 14 1.31e-11
R4 13 14 1.65e-1
C5 14 15 5.81e-10
L5 14 15 3.32e-12
R5 14 15 2.62e-1
C6 15 16 9.57e-11
L6 15 16 9.24e-12
R6 15 16 1.10
C7 16 17 1.69e-11
L7 16 17 1.94e-11
R7 16 17 2.53
C8 17 port2 4.90e-12
L8 17 port2 3.18e-11
R8 17 port2 1.00e+5
R100 port1 11 1.00e+11
.ENDS GCH0335C1H470JE01_DC0V_25degC