*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G/10pF/25V
* Murata P/N :GRM0335C1E100GA01
* Property : C = 10[pF]
* Data Generated on Apr 2, 2026
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-30GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1E100GA01_DC0V_25degC port1 port2
C1 port1 11 10.0e-12
L2 11 12 2.22e-10
R3 12 13 1.76e-1
L4 13 14 6.05e-12
R4 13 14 1.73
L5 14 15 1.81e-11
R5 14 15 3.10e-1
C6 15 16 1.44e-10
L6 15 16 2.42e-12
R6 15 16 5.07e-1
C7 16 17 1.60e-11
L7 16 17 8.08e-12
R7 16 17 3.67
C8 17 18 2.15e-11
L8 17 18 2.02e-12
R8 17 18 2.47
C9 18 port2 7.81e-12
L9 18 port2 3.10e-12
R9 18 port2 3.64
R100 port1 11 1.00e+10
.ENDS GRM0335C1E100GA01_DC0V_25degC