*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G/22pF/50V
* Murata P/N :GRM0335C1H220GA01
* Property : C = 22[pF]
* Data Generated on Apr 2, 2026
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-30GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H220GA01_DC0V_25degC port1 port2
C1 port1 11 2.20e-11
L2 11 12 1.73e-10
R3 12 13 1.42e-1
L4 13 14 4.03e-11
R4 13 14 13.8
L5 14 15 8.92e-12
R5 14 15 1.54e-1
C6 15 16 4.54e-10
L6 15 16 2.04e-12
R6 15 16 3.52e-1
C7 16 17 3.50e-11
L7 16 17 1.08e-11
R7 16 17 1.46
C8 17 18 9.92e-11
L8 17 18 1.14e-12
R8 17 18 4.96e-1
C9 18 port2 3.43e-11
L9 18 port2 1.64e-12
R9 18 port2 5.33e-1
R100 port1 11 1.00e+10
.ENDS GRM0335C1H220GA01_DC0V_25degC