*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R/1uF/50V
* Murata P/N :GRM155R61H105KE05
* Property : C = 1[uF]
* Data Generated on Mar 5, 2019
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 4.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61H105KE05_DC4V8_25degC port1 port2
C1 port1 11 4.89e-7
L2 11 12 1.30e-10
R3 12 13 9.64e-3
C4 13 14 3.69e-5
R4 13 14 66.0
C5 14 15 3.18e-5
R5 14 15 11.0
C6 15 16 2.45e-5
R6 15 16 1.65
C7 16 17 2.10e-5
R7 16 17 1.90e-1
C8 17 18 1.63e-5
R8 17 18 2.71e-2
C9 18 19 6.16e-5
R9 18 19 1.30e-3
L10 19 20 2.78e-11
R10 19 20 3.26e-1
L11 20 21 3.27e-11
R11 20 21 8.92e-2
L12 21 22 1.11e-10
R12 21 22 3.63e-2
C13 22 23 1.97e-6
L13 22 23 2.81e-11
R13 22 23 5.88e-3
C14 23 24 1.05e-6
L14 23 24 2.74e-11
R14 23 24 6.39e-3
C15 24 port2 4.56e-12
L15 24 port2 4.73e-11
R15 24 port2 9.97
R100 port1 11 5.00e+7
.ENDS GRM155R61H105KE05_DC4V8_25degC