*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R/0.1uF/50V
* Murata P/N :GRM155R61H104KE19
* Property : C = 0.1[uF]
* Data Generated on Nov 6, 2018
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 4.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61H104KE19_DC4V8_25degC port1 port2
C1 port1 11 9.87e-8
L2 11 12 1.90e-10
R3 12 13 1.45e-2
C4 13 14 1.41e-5
R4 13 14 283
C5 14 15 2.28e-5
R5 14 15 23.5
C6 15 16 2.22e-5
R6 15 16 3.03
C7 16 17 2.97e-5
R7 16 17 5.15e-1
C8 17 18 1.81e-5
R8 17 18 1.23e-1
C9 18 19 2.40e-5
R9 18 19 2.36e-2
C10 19 20 1.82e-5
R10 19 20 7.33e-3
L11 20 21 2.56e-11
R11 20 21 1.24e-1
L12 21 22 1.01e-10
R12 21 22 6.01e-2
C13 22 23 6.66e-7
L13 22 23 1.37e-11
R13 22 23 9.82e-3
C14 23 24 2.72e-7
L14 23 24 1.76e-11
R14 23 24 1.60e-2
C15 24 port2 1.01e-11
L15 24 port2 2.30e-11
R15 24 port2 2.18
R100 port1 11 5.00e+8
.ENDS GRM155R61H104KE19_DC4V8_25degC