*----------------------------------------------------------------------			
* SPICE Model generated by Murata Manufacturing Co., Ltd.			
* Copyright(C) Murata Manufacturing Co., Ltd.			
* MURATA P/N : 			
* Property : L = 1.0[uH]			
*----------------------------------------------------------------------			
* Applicable Conditions:			
*   Frequency Range = 1MHz - 110MHz			
*   Temperature = 25 degC			
*   DC Bias Current = 0 A			
*   Small Signal Operation			
*----------------------------------------------------------------------			
.SUBCKT	LQM18PH1R0MFC	port1	port2
L1	port1	2	0.283794u
L2	2	3	0.702124u
L3	3	4	0.0384762u
R1	port1	1	121.14
R2	2	3	1707.24
R3	3	4	0.69604
R4	4	port2	0.39
C1	port1	3	1.29238p
C2	1	2	63.7912p
.ENDS	LQM18PH1R0MFC		
*----------------------------------------------------------------------			
