*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/15pF/50V
* Murata P/N :GCH1555C1H150JE01
* Property : C = 15[pF]
* Data Generated on Jan 10, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCH1555C1H150JE01_DC0V_25degC port1 port2
C1 port1 11 1.50e-11
L2 11 12 2.37e-10
R3 12 13 1.06e-1
L4 13 14 2.01e-11
R4 13 14 4.00e-1
L5 14 15 3.51e-11
R5 14 15 1.05e-1
C6 15 16 1.06e-10
L6 15 16 1.01e-11
R6 15 16 1.61
C7 16 17 2.87e-11
L7 16 17 1.18e-11
R7 16 17 2.13
C8 17 port2 2.32e-12
L8 17 port2 8.88e-11
R8 17 port2 1.00e+5
R100 port1 11 1.00e+11
.ENDS GCH1555C1H150JE01_DC0V_25degC