*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R/0.47uF/10V
* Murata P/N :GCH155R61A474KE11
* Property : C = 0.47[uF]
* Data Generated on Apr 2, 2024
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 1.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCH155R61A474KE11_DC1V8_25degC port1 port2
C1 port1 11 3.71e-7
L2 11 12 1.64e-10
R3 12 13 2.94e-2
C4 13 14 1.04e-5
R4 13 14 382
C5 14 15 1.82e-5
R5 14 15 31.8
C6 15 16 1.60e-5
R6 15 16 5.27
C7 16 17 1.47e-5
R7 16 17 6.64e-1
C8 17 18 7.94e-5
R8 17 18 2.41e-1
C9 18 19 1.07e-5
R9 18 19 1.49e-1
C10 19 20 4.61e-6
R10 19 20 3.35e-2
L11 20 21 5.35e-11
R11 20 21 3.09e-1
L12 21 22 1.10e-10
R12 21 22 5.23e-2
C13 22 port2 4.59e-12
L13 22 port2 4.66e-11
R13 22 port2 7.49
R100 port1 11 1.06e+8
.ENDS GCH155R61A474KE11_DC1V8_25degC