*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X7R/47000pF/25V
* Murata P/N :GCH155R71E473KE01
* Property : C = 47000[pF]
* Data Generated on Nov 6, 2018
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 1.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCH155R71E473KE01_DC1V8_25degC port1 port2
C1 port1 11 4.78e-8
L2 11 12 1.80e-10
R3 12 13 2.29e-2
C4 13 14 4.82e-6
R4 13 14 901
C5 14 15 8.96e-6
R5 14 15 74.9
C6 15 16 5.74e-6
R6 15 16 24.2
C7 16 17 4.80e-6
R7 16 17 2.99
C8 17 18 4.27e-6
R8 17 18 3.56e-1
C9 18 19 3.35e-6
R9 18 19 7.11e-2
C10 19 20 3.23e-6
R10 19 20 1.15e-2
L11 20 21 1.55e-11
R11 20 21 1.19e-1
L12 21 22 7.11e-11
R12 21 22 9.19e-2
C13 22 23 8.47e-7
L13 22 23 5.08e-12
R13 22 23 7.91e-3
C14 23 24 5.60e-8
L14 23 24 3.57e-11
R14 23 24 3.22e-2
C15 24 port2 5.58e-12
L15 24 port2 5.53e-11
R15 24 port2 12.0
R100 port1 11 1.06e+9
.ENDS GCH155R71E473KE01_DC1V8_25degC