*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G/12pF/25V
* Murata P/N :GCM0335C1E120GA16
* Property : C = 12[pF]
* Data Generated on Apr 2, 2026
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-30GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM0335C1E120GA16_DC0V_25degC port1 port2
C1 port1 11 1.20e-11
L2 11 12 2.13e-10
R3 12 13 1.75e-1
L4 13 14 1.58e-11
R4 13 14 4.91
L5 14 15 1.67e-11
R5 14 15 2.10e-1
C6 15 16 1.77e-10
L6 15 16 2.30e-12
R6 15 16 3.95e-1
C7 16 17 2.07e-11
L7 16 17 7.42e-12
R7 16 17 2.63
C8 17 18 2.42e-11
L8 17 18 2.05e-12
R8 17 18 2.36
C9 18 19 4.89e-11
L9 18 19 5.22e-13
R9 18 19 9.66e-1
C10 19 port2 1.89e-11
L10 19 port2 9.28e-13
R10 19 port2 2.08
R100 port1 11 1.00e+11
.ENDS GCM0335C1E120GA16_DC0V_25degC