*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/560pF/50V
* Murata P/N :GCM1555C1H561JA16
* Property : C = 560[pF]
* Data Generated on Jan 10, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCM1555C1H561JA16_DC0V_25degC port1 port2
C1 port1 11 5.60e-10
L2 11 12 2.80e-10
R3 12 13 3.97e-2
L4 13 14 3.75e-11
R4 13 14 1.15
L5 14 15 1.97e-11
R5 14 15 2.04e-2
C6 15 16 4.90e-9
L6 15 16 8.02e-12
R6 15 16 2.17e-1
C7 16 17 9.84e-10
L7 16 17 1.73e-11
R7 16 17 5.27e-1
C8 17 port2 4.32e-10
L8 17 port2 1.09e-11
R8 17 port2 2.25e-1
R100 port1 11 1.00e+11
.ENDS GCM1555C1H561JA16_DC0V_25degC