*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/20pF/50V
* Murata P/N :GCQ1555C1H200JB01
* Property : C = 20[pF]
* Data Generated on Apr 1, 2025
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-20GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCQ1555C1H200JB01_DC0V_25degC port1 port2
C1 port1 11 2.00e-11
L2 11 12 2.14e-10
R3 12 13 7.29e-2
L4 13 14 3.90e-12
R4 13 14 3.98e-2
C5 14 15 1.01e-10
L5 14 15 1.21e-11
R5 14 15 12.0
C6 15 16 2.60e-11
L6 15 16 1.99e-11
R6 15 16 26.5
C7 16 17 1.16e-10
L7 16 17 2.23e-12
R7 16 17 4.20
C8 17 18 2.66e-11
L8 17 18 6.15e-12
R8 17 18 13.9
C9 18 19 1.01e-10
L9 18 19 1.07e-12
R9 18 19 3.04
C10 19 20 2.56e-11
L10 19 20 3.11e-12
R10 19 20 12.4
C11 20 21 6.94e-11
L11 20 21 8.83e-13
R11 20 21 2.97
C12 21 22 2.00e-11
L12 21 22 2.43e-12
R12 21 22 11.8
C13 22 23 1.73e-11
L13 22 23 2.31e-12
R13 22 23 6.84
C14 23 24 5.98e-12
L14 23 24 5.69e-12
R14 23 24 24.5
C15 24 port2 2.88e-12
L15 24 port2 9.74e-12
R15 24 port2 39.6
R100 port1 11 1.00e+10
.ENDS GCQ1555C1H200JB01_DC0V_25degC