*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/39pF/50V
* Murata P/N :GCQ1555C1H390GB01
* Property : C = 39[pF]
* Data Generated on Sep 11, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GCQ1555C1H390GB01_DC0V_25degC port1 port2
C1 port1 11 3.90e-11
L2 11 12 1.93e-10
R3 12 13 7.00e-2
C4 13 14 1.86e-10
L4 13 14 1.33e-11
R4 13 14 6.39
C5 14 15 5.35e-11
L5 14 15 1.94e-11
R5 14 15 13.5
C6 15 16 1.09e-10
L6 15 16 4.73e-12
R6 15 16 2.81
C7 16 17 1.05e-10
L7 16 17 3.24e-12
R7 16 17 2.69
C8 17 port2 4.72e-12
L8 17 port2 5.63e-11
R8 17 port2 1.00e+5
R100 port1 11 1.00e+11
.ENDS GCQ1555C1H390GB01_DC0V_25degC