*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/C0G/27pF/50V
* Murata P/N :GRM0335C1H270JA01
* Property : C = 27[pF]
* Data Generated on Jan 10, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100MHz-8.5GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM0335C1H270JA01_DC0V_25degC port1 port2
C1 port1 11 2.70e-11
L2 11 12 1.44e-10
R3 12 13 1.49e-1
L4 13 14 1.21e-11
R4 13 14 2.27e-1
C5 14 15 8.90e-12
L5 14 15 3.91e-11
R5 14 15 4.42
C6 15 port2 3.63e-12
L6 15 port2 5.39e-11
R6 15 port2 1.00e+5
R100 port1 11 1.00e+10
.ENDS GRM0335C1H270JA01_DC0V_25degC