*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R/1uF/25V
* Murata P/N :GRM155R61E105KE11
* Property : C = 1[uF]
* Data Generated on Oct 1, 2020
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 1.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61E105KE11_DC1V8_25degC port1 port2
C1 port1 11 7.40e-7
L2 11 12 1.41e-10
R3 12 13 8.92e-3
C4 13 14 2.39e-5
R4 13 14 125
C5 14 15 3.04e-5
R5 14 15 12.0
C6 15 16 2.87e-5
R6 15 16 1.62
C7 16 17 2.70e-5
R7 16 17 2.35e-1
C8 17 18 2.23e-5
R8 17 18 4.24e-2
C9 18 19 1.81e-5
R9 18 19 1.08e-2
L10 19 20 2.15e-11
R10 19 20 1.86e-1
L11 20 21 2.78e-11
R11 20 21 1.02e-1
L12 21 22 1.31e-10
R12 21 22 3.36e-2
C13 22 23 3.66e-6
L13 22 23 2.02e-11
R13 22 23 4.08e-3
C14 23 24 1.76e-6
L14 23 24 2.38e-11
R14 23 24 5.22e-3
C15 24 port2 7.60e-12
L15 24 port2 3.96e-11
R15 24 port2 10.9
R100 port1 11 5.00e+7
.ENDS GRM155R61E105KE11_DC1V8_25degC