*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/1000pF/50V
* Murata P/N :GRM1555C1H102JA01
* Property : C = 1000[pF]
* Data Generated on Jan 10, 2017
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1MHz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H102JA01_DC0V_25degC port1 port2
C1 port1 11 9.93e-10
L2 11 12 9.26e-11
R3 12 13 1.46e-2
L4 13 14 1.36e-10
R4 13 14 2.95e-2
C5 14 15 5.86e-9
L5 14 15 1.40e-11
R5 14 15 2.91e-1
C6 15 16 1.79e-9
L6 15 16 2.06e-11
R6 15 16 4.45e-1
C7 16 17 2.01e-12
L7 16 17 1.29e-10
R7 16 17 1.00e+5
C8 17 port2 6.84e-13
L8 17 port2 6.98e-11
R8 17 port2 9.47e-1
R100 port1 11 1.00e+10
.ENDS GRM1555C1H102JA01_DC0V_25degC