*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R/0.1uF/50V
* Murata P/N :GRM155R61H104KE19
* Property : C = 0.1[uF]
* Data Generated on Nov 6, 2018
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 1.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61H104KE19_DC1V8_25degC port1 port2
C1 port1 11 1.01e-7
L2 11 12 1.90e-10
R3 12 13 1.45e-2
C4 13 14 1.47e-5
R4 13 14 271
C5 14 15 2.39e-5
R5 14 15 22.5
C6 15 16 2.33e-5
R6 15 16 2.90
C7 16 17 3.11e-5
R7 16 17 4.92e-1
C8 17 18 1.89e-5
R8 17 18 1.18e-1
C9 18 19 2.51e-5
R9 18 19 2.26e-2
C10 19 20 1.90e-5
R10 19 20 7.01e-3
L11 20 21 2.56e-11
R11 20 21 1.24e-1
L12 21 22 1.01e-10
R12 21 22 5.98e-2
C13 22 23 6.82e-7
L13 22 23 1.37e-11
R13 22 23 9.61e-3
C14 23 24 2.78e-7
L14 23 24 1.76e-11
R14 23 24 1.57e-2
C15 24 port2 1.01e-11
L15 24 port2 2.30e-11
R15 24 port2 2.18
R100 port1 11 5.00e+8
.ENDS GRM155R61H104KE19_DC1V8_25degC