*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/X5R/0.47uF/50V
* Murata P/N :GRM155R61H474KE11
* Property : C = 0.47[uF]
* Data Generated on Nov 6, 2018
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100Hz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 1.8V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM155R61H474KE11_DC1V8_25degC port1 port2
C1 port1 11 3.49e-7
L2 11 12 1.71e-10
R3 12 13 1.85e-2
C4 13 14 1.19e-5
R4 13 14 335
C5 14 15 1.61e-5
R5 14 15 33.5
C6 15 16 1.76e-5
R6 15 16 4.12
C7 16 17 1.47e-5
R7 16 17 8.61e-1
C8 17 18 1.01e-5
R8 17 18 1.52e-1
C9 18 19 1.43e-4
R9 18 19 1.33e-1
C10 19 20 5.26e-6
R10 19 20 2.74e-2
L11 20 21 2.89e-11
R11 20 21 3.25e-1
L12 21 22 3.26e-11
R12 21 22 7.09e-2
L13 22 23 1.17e-10
R13 22 23 4.02e-2
C14 23 24 5.70e-7
L14 23 24 4.47e-11
R14 23 24 6.45e-3
C15 24 port2 6.13e-12
L15 24 port2 4.16e-11
R15 24 port2 7.77
R100 port1 11 1.06e+8
.ENDS GRM155R61H474KE11_DC1V8_25degC