*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :1005M(0402)/C0G/4700pF/50V
* Murata P/N :GRM1555C1H472JE01
* Property : C = 4700[pF]
* Data Generated on Mar 5, 2019
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 1MHz-6GHz
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM1555C1H472JE01_DC0V_25degC port1 port2
C1 port1 11 4.67e-9
L2 11 12 2.43e-10
R3 12 13 3.17e-3
L4 13 14 2.64e-11
R4 13 14 2.43e-1
L5 14 15 2.48e-11
R5 14 15 2.34e-2
L6 15 16 8.00e-11
R6 15 16 9.00e-3
L7 16 17 3.56e-10
R7 16 17 3.73e-3
C8 17 18 2.96e-8
L8 17 18 1.09e-11
R8 17 18 1.44e-1
C9 18 19 7.18e-9
L9 18 19 1.89e-11
R9 18 19 2.45e-1
C10 19 20 4.35e-9
L10 19 20 9.40e-12
R10 19 20 1.09e-1
C11 20 port2 1.65e-11
L11 20 port2 1.90e-11
R11 20 port2 16.3
R100 port1 11 1.00e+10
.ENDS GRM1555C1H472JE01_DC0V_25degC